### ISSUE TITLE
请问有没有尝试过别的文本生成任务呢？

### ISSUE THREAD

**Issue by bojone** [Edward-Sun/structured-nart#2]
（我看了一下作者也是中国人，我就直接用中文提问啦）

你好，最近留意到了您的这个工作，细读了一下。尽管没有看到源码，但论文对模型的描述还算详细，所以我感觉我应该没有理解错。因此我有如下的一些疑惑。

首先，这篇文章应该是纯粹将机器翻译问题转化为CRF序列标注问题，除了模型架构有些特别之外，形式上应该跟普通的序列标注没啥差别。尽管CRF所建立的概率分布比逐帧softmax要复杂一些，但我觉得它应该是不足以描述一个句子的概率的（因为CRF本质上也就是一个2-gram语言模型）。

然后，我注意到，论文所评测的任务只是机器翻译任务，而且是En-De，这两种语言之间的翻译相对来说比较简单，而且比较对齐（这也是为什么能将长度设为T'=T+C）。再换个角度看，哪怕直接逐词翻译，也能获得（相对）不错的bleu值。所以我感觉单评测机器翻译任务，不足以完整验证一个非自回归生成模型。

不知道作者们有没有在别的文本生成任务上评测过呢？比如摘要类的？或者语法形态差异比较大的机器翻译任务上验证过呢？

（我自己也参考贵论文的思路，实现了一些基于序列标注的文章标题生成模型，发现生成的标题并没有想象中那么理想，遂来此请教。）

**Comment by Edward-Sun** [comment]
嗨，你好，欢迎关注我们的工作。 关于源码，可以参考Jiatao在fairseq中对我们模型的复现，这可以达到我们paper claim的结果。

是的，CRF是不足以描述一个句子的概率的，这需要unitary score，即普通的NART的结果也不错，然后在此之上进行提升。

我们还没有在别的任务上测过，因为如同上面所说的，structured-nart这个模型需要普通的nart结果也不错才行，如果multimodality问题太严重就没办法。
