### ISSUE TITLE
A question about the CRF implementation

### ISSUE THREAD

**Issue by speedcell4** [Edward-Sun/structured-nart#4]
Hi~ 
Thanks for the upcoming code.

I have a question about your CRF implementation. 
As [[Rush, 2020]](https://www.aclweb.org/anthology/2020.acl-demos.38.pdf) mentioned, leveraging the commutative property of matrix multiplication operation and applying tree reduction can reduce the time complexity for obtaining the partition function, i.e., `Z(x)`, from O(n) to O(log n). 
My question is, which implementation did you use? The speedup numbers in Table 2 are based on which implementation?

**Comment by Edward-Sun** [comment]
We didn't use tree reduction, so the complexity is O(n)
